# This workflow will build and upload test artifact
# Simple workflow with ignoring condition to prevent unneccessary build
# To download artifact check on job task

name: Build Test and Upload Artifical

on:
  push:
    branches:
        - 'main'

permissions:
  contents: read

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: gradle

      - name: Fix Gradle permission
        run: chmod +x ./gradlew

      - name: Build Jars
        run: ./gradlew build

      - name: Upload Artifical
        id: upload-job
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ActualLegacyInstaller-build.${{ github.run_number}}.jar
          path: build/libs
          if-no-files-found: error